browser = chrome
url = https://naveenautomationlabs.com/opencart/index.php?route=account/login
username = qapanipuri999@gmail.com
password = qapanipuri999

headless = false
incognito = false

remote = true
huburl = http://localhost:4444/wd/hub
