browser = firefox
url = https://naveenautomationlabs.com/opencart/index.php?route=account/login
username = qapanipuri999@gmail.com
password = qapanipuri999

headless =
incognito =

remote =
remote_url =
